### ISSUE TITLE
Mega Charizard's penis much too large

### ISSUE THREAD

**Issue by javacola** [Touched/MegaEvolution#11]
Touched,

I've encountered a problem when activating your mega evolution routine with charizard. The effect seems to multiply the size of his penis far too much and it ends up tearing my butthole and not being pleasurable at all. I eat a lot of spanish food as it is so my shits burn like hell already. This isn't helping things. Please get this fixed and release a patch asap.

Thanks.

**Comment by Touched** [comment]
Closing this because you didn't say whether it was Charizard X or Charizard Y.

**Comment by Exodrake** [comment]
But what if it's a female?
