### ISSUE TITLE
Mega evolution change level

### ISSUE THREAD

**Issue by aiolialeo** [Touched/MegaEvolution#27]
Hey! Some of my testers found this using your engine. Turns that when mega evolve, some pokémon changes its levels. I don't know what can I do. I might send you my rom if you desire so. Thanks in advance!

[img]http://i.imgur.com/lJNWYxe.jpg[/img]
[img]http://i.imgur.com/7o9ztKa.jpg[/img]

[http://www.mediafire.com/file/vghg2g08x1c4t9t/Pokemon-Shiny-Gold-Sigma12.6.zip](url)

**Comment by sphericalice** [comment]
You've just set different XP Curve for the base Pokemon and its Mega forme.

**Comment by aiolialeo** [comment]
@sphericalice can't thank you enough!
